NAME = a.out

CC = c++

FLAGS = -Wall -Wextra -Werror -std=c++98

RM = rm -rf

SRCS = main.cpp\
	Warlock.cpp\
	ASpell.cpp\
	ATarget.cpp\
	Fwoosh.cpp\
	Dummy.cpp\
	Fireball.cpp\
	Polymorph.cpp\
	BrickWall.cpp\
	SpellBook.cpp\
	TargetGenerator.cpp\

OBJS = $(SRCS:.cpp=.o)

$(NAME): $(OBJS)
	@ $(CC) $(FLAGS) $(OBJS) -o $(NAME)

$(OBJS):    ./%.o : ./%.cpp
	@ $(CC) $(FLAGS) -c $< -o $@

all: $(NAME)

clean:
	@ $(RM) $(OBJS)

fclean:
	@ $(RM) $(NAME) $(OBJS)

re : fclean all

.PHONY : all re fclean clean

